# Generated by Django 4.2.7 on 2024-08-09 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="avatar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avatar",
                to="users.profile",
            ),
        ),
    ]
