# Generated by Django 4.2.7 on 2024-08-28 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("goods", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Basket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=None, null=True, verbose_name="количество"
                    ),
                ),
                (
                    "date",
                    models.CharField(
                        default="Wed Aug 28 2024 21:19:39 GMT+0300 (Europe/Moscow)",
                        max_length=100,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=None, null=True, verbose_name="номер заказа"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="goods.product",
                        verbose_name="товар",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="имя пользоваткля",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар_в_корзине_пользователя",
                "verbose_name_plural": "Товары в корзинах пользователей",
                "ordering": ["id"],
            },
        ),
    ]
