# Generated by Django 4.2.7 on 2024-08-12 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0008_product_rating_specifications"),
        ("basket", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="basket",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="basket",
            name="date_added",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="basket",
            name="session_key",
            field=models.CharField(default="default_session_key", max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="basket",
            unique_together={("session_key", "product")},
        ),
        migrations.RemoveField(
            model_name="basket",
            name="user",
        ),
    ]
