# Generated by Django 4.2.7 on 2024-08-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0002_alter_basket_unique_together_basket_date_added_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basket",
            name="session_key",
            field=models.CharField(max_length=255),
        ),
    ]
