# Generated by Django 4.2.7 on 2024-08-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="banners",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="popular",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="sales",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.CharField(
                default="Wed Aug 28 2024 21:36:29 GMT+0300 (Europe/Moscow)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="limited",
            field=models.BooleanField(default=False),
        ),
    ]
