# Generated by Django 4.2.7 on 2024-08-29 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0002_product_banners_product_popular_product_sales_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="goods.product",
                verbose_name="товар",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.CharField(
                default="Thu Aug 29 2024 20:43:48 GMT+0300 (Europe/Moscow)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=100, verbose_name="название"),
        ),
        migrations.RemoveField(
            model_name="tag",
            name="product",
        ),
        migrations.AddField(
            model_name="tag",
            name="product",
            field=models.ManyToManyField(
                related_name="tags", to="goods.product", verbose_name="товар"
            ),
        ),
    ]
