# Generated by Django 4.2.7 on 2024-07-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0002_alter_product_category_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="category_id",
            new_name="category",
        ),
        migrations.AlterField(
            model_name="image",
            name="src",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
