# Generated by Django 4.2.7 on 2024-07-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0003_rename_category_id_product_category_alter_image_src"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
