# Generated by Django 4.2.7 on 2024-08-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0003_alter_image_product_alter_product_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specifications",
            options={
                "ordering": ["id"],
                "verbose_name": "Спецификация",
                "verbose_name_plural": "Спецификации",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.CharField(
                default="Thu Aug 29 2024 21:17:49 GMT+0300 (Europe/Moscow)",
                max_length=100,
            ),
        ),
    ]
