# Generated by Django 4.2.7 on 2024-08-30 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0004_alter_specifications_options_alter_product_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.CharField(
                default="Fri Aug 30 2024 06:38:51 GMT+0300 (Europe/Moscow)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="дата"
            ),
        ),
    ]
