# Generated by Django 4.2.7 on 2024-08-02 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0004_alter_tag_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="free_delivery",
            new_name="freeDelivery",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="full_description",
            new_name="fullDescription",
        ),
    ]
