# Generated by Django 4.2.7 on 2024-08-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0005_rename_free_delivery_product_freedelivery_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="src",
            field=models.ImageField(upload_to=""),
        ),
    ]
