# Generated by Django 4.2.7 on 2024-08-09 05:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0006_alter_image_src"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
