# Generated by Django 4.2.7 on 2024-08-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0008_product_rating_specifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="banners",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="limited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="popular",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="sales",
            field=models.BooleanField(default=False),
        ),
    ]
