# Generated by Django 4.2.7 on 2024-08-23 17:55

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0009_product_banners_product_limited_product_popular_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="dateFrom",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="product",
            name="dateTo",
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 23, 0, 0)),
        ),
        migrations.AddField(
            model_name="product",
            name="salePrice",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
