# Generated by Django 4.2.7 on 2024-08-12 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoryimage",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="categoryimage",
            name="subcategories",
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_image",
                to="catalog.categoryimage",
            ),
        ),
    ]
