# Generated by Django 4.2.7 on 2024-08-12 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_remove_categoryimage_categories_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CategoryImage",
            new_name="Image",
        ),
        migrations.AddField(
            model_name="subcategory",
            name="image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategory_image",
                to="catalog.image",
            ),
        ),
    ]
