# Generated by Django 4.2.7 on 2024-08-13 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_rename_categoryimage_image_subcategory_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("salePrice", models.DecimalField(decimal_places=2, max_digits=10)),
                ("dateFrom", models.DateField()),
                ("dateTo", models.DateField()),
                ("title", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SaleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("src", models.ImageField(upload_to="")),
                ("alt", models.CharField(max_length=255)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.saleproduct",
                    ),
                ),
            ],
        ),
    ]
