# Generated by Django 4.2.7 on 2024-08-23 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_saleproduct_saleimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SaleImage",
        ),
        migrations.DeleteModel(
            name="SaleProduct",
        ),
    ]
