# Generated by Django 4.2.7 on 2024-08-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(max_length=16)),
                ("name", models.CharField(max_length=128)),
                ("month", models.IntegerField(max_length=2)),
                ("year", models.IntegerField(max_length=2)),
                ("code", models.IntegerField(max_length=3)),
            ],
        ),
    ]
