# Generated by Django 4.2.7 on 2024-08-30 18:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_alter_payment_code_alter_payment_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="order",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="orders.order",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payment",
            name="code",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(999),
                    django.core.validators.MinValueValidator(0),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="month",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(99),
                    django.core.validators.MinValueValidator(0),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="number",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(9999999999999999),
                    django.core.validators.MinValueValidator(0),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="year",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(99),
                    django.core.validators.MinValueValidator(0),
                ]
            ),
        ),
    ]
