# Generated by Django 4.2.7 on 2024-08-23 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now=True, verbose_name="дата")),
                (
                    "fullName",
                    models.CharField(
                        blank=True,
                        default="anonymous",
                        max_length=100,
                        null=True,
                        verbose_name="полное имя заказчика",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=100, null=True, verbose_name="почта"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="телефон"
                    ),
                ),
                (
                    "deliveryType",
                    models.CharField(
                        choices=[
                            ("ordinary", "Доставка"),
                            ("express", "Экспресс-доставка"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="тип доставки",
                    ),
                ),
                (
                    "paymentType",
                    models.CharField(
                        choices=[
                            ("online", "Онлайн картой"),
                            ("someone", "Онлайн со случайного чужого счёта"),
                        ],
                        db_index=True,
                        max_length=40,
                        verbose_name="тип оплаты",
                    ),
                ),
                (
                    "totalCost",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=8,
                        null=True,
                        verbose_name="полная стоимость",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in processing", "В обработке"),
                            ("paid", "Оплачено"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        default=None, max_length=100, null=True, verbose_name="город"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        default=None, max_length=400, null=True, verbose_name="адрес"
                    ),
                ),
                (
                    "products",
                    models.FileField(
                        default="None",
                        null=True,
                        upload_to="",
                        verbose_name="Файл продуктов заказа",
                    ),
                ),
                (
                    "order_name",
                    models.CharField(
                        default=None,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Файл заказа",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["id"],
            },
        ),
    ]
