# Generated by Django 4.2.7 on 2024-08-30 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("goods", "0005_alter_product_date_alter_review_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now=True, verbose_name="дата")),
                (
                    "fullName",
                    models.CharField(
                        blank=True,
                        default="anonymous",
                        max_length=100,
                        null=True,
                        verbose_name="полное имя заказчика",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=100, null=True, verbose_name="почта"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="телефон"
                    ),
                ),
                (
                    "deliveryType",
                    models.CharField(
                        choices=[
                            ("ordinary", "Доставка"),
                            ("express", "Экспресс-доставка"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="тип доставки",
                    ),
                ),
                (
                    "paymentType",
                    models.CharField(
                        choices=[
                            ("online", "Онлайн картой"),
                            ("someone", "Онлайн со случайного чужого счёта"),
                        ],
                        db_index=True,
                        max_length=40,
                        verbose_name="тип оплаты",
                    ),
                ),
                (
                    "totalCost",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=8,
                        null=True,
                        verbose_name="полная стоимость",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in processing", "В обработке"),
                            ("paid", "Оплачено"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="статус",
                    ),
                ),
                (
                    "city",
                    models.CharField(max_length=100, null=True, verbose_name="город"),
                ),
                (
                    "address",
                    models.CharField(max_length=400, null=True, verbose_name="адрес"),
                ),
                (
                    "order_name",
                    models.CharField(
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Название заказа",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="OrderProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_products",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_products",
                        to="goods.product",
                    ),
                ),
            ],
        ),
    ]
