# Generated by Django 4.2.7 on 2024-08-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0010_product_datefrom_product_dateto_product_saleprice"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(max_length=400, null=True, verbose_name="адрес"),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(max_length=100, null=True, verbose_name="город"),
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_name",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="Название заказа"
            ),
        ),
        migrations.RemoveField(
            model_name="order",
            name="products",
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                related_name="orders",
                to="goods.product",
                verbose_name="Продукты заказа",
            ),
        ),
    ]
